name: Convert Markdown to HTML with Marpit

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install Marpit CLI
      run: npm install -g @marp-team/marp-cli

    - name: Create output directory
      run: mkdir -p pageshtml

    - name: Convert Markdown to HTML
      run: |
        # Install find and xargs if not available
        sudo apt-get update
        sudo apt-get install -y findutils
        
        # Find all .md files in pagesmd and convert them to HTML
        find pagesmd -name '*.md' | while read -r file; do
          # Create output directory structure
          out_dir="pageshtml/$(dirname "${file#pagesmd/}")"
          mkdir -p "$out_dir"
          
          # Convert with Marpit
          marpit "$file" -o "${out_dir}/$(basename "$file" .md).html"
        done

    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add pageshtml/
        git diff --quiet && git diff --staged --quiet || \
        (git commit -m "Auto-generated HTML files [skip ci]" && git push)

    - name: Deploy to Remote Server
      run: |
        if [ -f ".github/workflows/copy-to-ionos.yml" ]; then
          # Install SSH and SSHPass
          sudo apt-get update
          sudo apt-get install -y sshpass

          # Clean remote directory
          sshpass -p "${{ secrets.ROOT_PWD }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.REMOTE_HOST }} "rm -rf ~/marp/pageshtml/"

          # Deploy files via rsync
          sshpass -p "${{ secrets.ROOT_PWD }}" rsync -av --exclude='.github' --exclude='.git' ./pageshtml/ root@${{ secrets.REMOTE_HOST }}:~/marp/pageshtml/
        fi
